### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by stemangiola** [nullranges/tidy-ranges-tutorial#2]
Very well done! I give some feedback. Obviously, don't feel you have to address any of this.

1. as a user, it would be nice to have a print-on-screen of the object `gse` somewhere at the beginning
2. If `gse` is a SummarizedExperiment, you don’t need to call `tidybulk`; all tidy tools work natively on SummarizedExperiment.
3. You seem to be able to use “filter” without importing tidySummarizedExperiment
4. Any reason you need to specify levels here? -> factor(.sample, levels=unique(.sample))
5. Very personal preference: In the tidytranscriptomics manifesto, we state that it is preferable not to transform data for plotting, so lowering the barrier to understanding. For example instead of logging the data `ggplot(aes(.sample, log10(counts_scaled + 1)))` I would use `ggplot(aes(.sample, counts_scaled + 1)) + … + scale_y_log_10()`.

**Comment by mikelove** [comment]
Thanks for the feedback!

4. setting levels via `unique` were so untreated go on the left in the ggplots. I can clarify

All other are good points and I will make these changes :)

**Comment by mikelove** [comment]
Oh yeah, I tried to avoid conversion with `tidybulk()` but then these lines are not allowed:

https://github.com/nullranges/tidy-ranges-tutorial/blob/main/tidy-rna-seq-eda.Rmd#L129-L132

It said something along the lines of not being able to modify `.sample`, but having to make a copy.

**Comment by stemangiola** [comment]
> It said something along the lines of not being able to modify `.sample`, but having to make a copy.

I see. Yes I guess a little change of mentality is that, in contrast with base R, .sample column (colnames(SE)) behaves no differently that any other sample-wise column (and you see those in the same abstraction), so there is no cost for downstream analyses in defining and using a `sample_formatted` column.

I would think is better to leave .sample (colnames(SE)) immutated for reproducibillity/future reference, and create a new column that can be used in visualisation or analysis. The tidy API reconciles the behaviour of column names with colData. all of them are simply a column.

Something like
```r
 mutate(sample_formatted = .sample |> str_remove("OCT4-") |> fct_relevel(c("untr-1", "untr-2",...))
```

In my very very personal opinion, just for chatter, the beauty of factor relevel is that users do not have to guess why of the `levels=unique(.sample))`, making the code more transparent, and less reliant on documentation (a great direction promoted by tidyverse).

**Comment by mikelove** [comment]
Thanks again!
