### ISSUE TITLE
Smoother liftover for working with ranges in different genome builds

### ISSUE THREAD

**Issue by mikelove** [nullranges/tidy-ranges-tutorial#4]
Improve liftover operation for working with GRanges. This probably should live in a new package, maybe *easylift*? I'd be happy to work with someone interested in writing their first Bioconductor package.

Currently the operations are:

- Find chain file on UCSC website
- Download
- Unzip
- `rtracklayer::import`
- `rtracklayer::liftOver`
- `unlist`
- `genome()<-` (what about seqinfo/seqlengths?)

From Herve (on tech-advisory-board channel)

"With this improvement to getChromInfoFromUCSC(), the standard way to set the Seqinfo on the lifted object becomes:"

```
to_seqinfo <- getChromInfoFromUCSC("hg19", assembled.molecules.only=TRUE, as.Seqinfo=TRUE)
lifted_seqlevels <- seqlevels(cur)[genome(cur) %in% "hg38"]
seqinfo(cur19) <- update(seqinfo(cur19), to_seqinfo[lifted_seqlevels])
```

with the relevant commit to GenomeInfoDb:

https://github.com/Bioconductor/GenomeInfoDb/commit/345f22c55b8c431f1cf8080af3235f78266ade9c

**Comment by nahid18** [comment]
Professor @mikelove, I want to write my first Bioconductor package. How can I work with you on this? 
Thanks.

**Comment by mikelove** [comment]
feel free to call me Mike :)

sure, i'd be happy to work with you on this. let me connect with you on a Bioc slack channel

**Comment by nahid18** [comment]
thanks

**Comment by mikelove** [comment]
Discussion on #easylift on the community-bioc Slack channel

**Comment by mikelove** [comment]
Proposal for the function usage:

```
new_gr <- easylift(gr, to="hg38", chain="...")
```

It would expect that `genome(gr)` is provided, e.g. in this case maybe it is `"hg19"`.

**Comment by nahid18** [comment]
initial implementation: [https://github.com/nahid18/easylift](https://github.com/nahid18/easylift)
